# Generated by Django 4.2.7 on 2023-12-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0006_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Основание',
                'verbose_name_plural': 'Основания',
                'db_table': 'basis',
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Высота')),
                ('witdh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ширина')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Длина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаленный')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True, verbose_name='Широта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ended_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('basis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.basis')),
            ],
            options={
                'verbose_name': 'Строительство',
                'verbose_name_plural': 'Строительства',
                'db_table': 'construction',
            },
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Тип строительства',
                'verbose_name_plural': 'Типы строительства',
                'db_table': 'construction_type',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('attr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='WhereIsBuilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('attr', models.CharField(max_length=255, verbose_name='Атрибут')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Где строится',
                'verbose_name_plural': 'Где строится',
                'db_table': 'where_is_built',
            },
        ),
        migrations.CreateModel(
            name='SeasonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('construction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.constructiontype')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.season')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Цена сезона',
                'verbose_name_plural': 'Цены сезонов',
                'db_table': 'season_price',
            },
        ),
        migrations.CreateModel(
            name='ConstructionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.construction')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state')),
            ],
            options={
                'verbose_name': 'Изображение строительства',
                'verbose_name_plural': 'Изображения строительств',
                'db_table': 'construction_image',
            },
        ),
        migrations.AddField(
            model_name='construction',
            name='construction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.constructiontype'),
        ),
        migrations.AddField(
            model_name='construction',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.district'),
        ),
        migrations.AddField(
            model_name='construction',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.neighborhood'),
        ),
        migrations.AddField(
            model_name='construction',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.region'),
        ),
        migrations.AddField(
            model_name='construction',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.season'),
        ),
        migrations.AddField(
            model_name='construction',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state'),
        ),
        migrations.AddField(
            model_name='construction',
            name='where_is_built',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.whereisbuilt'),
        ),
        migrations.AddIndex(
            model_name='construction',
            index=models.Index(fields=['title'], name='constructio_title_719893_idx'),
        ),
        migrations.AddIndex(
            model_name='construction',
            index=models.Index(fields=['construction_type'], name='constructio_constru_15e935_idx'),
        ),
        migrations.AddIndex(
            model_name='construction',
            index=models.Index(fields=['season'], name='constructio_season__44f45f_idx'),
        ),
        migrations.AddIndex(
            model_name='construction',
            index=models.Index(fields=['created_at'], name='constructio_created_69fd8f_idx'),
        ),
    ]
