# Generated by Django 4.2.7 on 2024-01-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество строительств')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена сезона (миллион сумов)')),
                ('construction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.constructiontype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.season')),
            ],
            options={
                'verbose_name': 'Статистика сезона',
                'verbose_name_plural': 'Статистика сезонов',
                'db_table': 'season_stat',
            },
        ),
    ]
