# Generated by Django 4.2.7 on 2024-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seasonstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructiontype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='construction_type', verbose_name='Изображение'),
        ),
    ]
