# Generated by Django 4.2.7 on 2023-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_state_name_en_state_name_ru_state_name_uz_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='erp_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='soato_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='erp_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='soato_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
