# Generated by Django 4.2.7 on 2024-01-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('app', '0001_initial'),
        ('utils', '0006_language'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='title',
        ),
        migrations.AlterField(
            model_name='votes',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.construction', verbose_name='Строительство'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user', verbose_name='Пользователь'),
        ),
    ]
